services:
  - type: web
    name: stephano-portfolio
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /actuator/health
    envVars:
      - key: GITHUB_TOKEN
        sync: false
